import { ScanResult, Violation } from '../types';
import * as fs from 'fs';
import * as path from 'path';

export class ReportGenerator {
  generateMarkdownReport(result: ScanResult): string {
    const lines: string[] = [];

    lines.push('# Etsy Compliance Check Report');
    lines.push('');
    lines.push(`**Shop ID:** ${result.shop_id}`);
    lines.push(`**Scan Date:** ${result.scan_date}`);
    lines.push(`**Total Listings Scanned:** ${result.scanned_listings} / ${result.total_listings}`);
    lines.push('');

    lines.push('## Summary');
    lines.push('');
    lines.push(`- 🔴 **Critical Violations:** ${result.summary.critical}`);
    lines.push(`- ⚠️  **Warnings:** ${result.summary.warnings}`);
    lines.push(`- ℹ️  **Info:** ${result.summary.info}`);
    lines.push('');

    if (result.violations.length === 0) {
      lines.push('✅ **No violations found! Your shop is compliant.**');
      lines.push('');
      return lines.join('\n');
    }

    // Group violations by severity
    const critical = result.violations.filter(v => v.severity === 'critical');
    const warnings = result.violations.filter(v => v.severity === 'warning');
    const info = result.violations.filter(v => v.severity === 'info');

    if (critical.length > 0) {
      lines.push('## 🔴 Critical Violations (Immediate Action Required)');
      lines.push('');
      lines.push('These violations may result in listing removal or shop suspension.');
      lines.push('');
      this.addViolationDetails(lines, critical);
    }

    if (warnings.length > 0) {
      lines.push('## ⚠️  Warnings (Review Recommended)');
      lines.push('');
      lines.push('These issues should be addressed to improve compliance.');
      lines.push('');
      this.addViolationDetails(lines, warnings);
    }

    if (info.length > 0) {
      lines.push('## ℹ️  Informational (Best Practices)');
      lines.push('');
      lines.push('Suggestions to improve your listings.');
      lines.push('');
      this.addViolationDetails(lines, info);
    }

    lines.push('---');
    lines.push('');
    lines.push('*Generated by Etsy Compliance Checker*');
    lines.push('');

    return lines.join('\n');
  }

  private addViolationDetails(lines: string[], violations: Violation[]): void {
    // Group by listing
    const byListing = new Map<number, Violation[]>();

    for (const violation of violations) {
      if (!byListing.has(violation.listing_id)) {
        byListing.set(violation.listing_id, []);
      }
      byListing.get(violation.listing_id)!.push(violation);
    }

    for (const [listingId, listingViolations] of byListing) {
      const first = listingViolations[0];
      lines.push(`### Listing: ${first.listing_title}`);
      lines.push('');
      lines.push(`**Listing ID:** ${listingId}`);
      lines.push(`**URL:** ${first.listing_url}`);
      lines.push('');
      lines.push('**Issues:**');
      lines.push('');

      for (const violation of listingViolations) {
        lines.push(`- **${violation.category}**: ${violation.message}`);
        if (violation.matched_keyword) {
          lines.push(`  - Matched keyword: \`${violation.matched_keyword}\``);
        }
      }

      lines.push('');
    }
  }

  generateJsonReport(result: ScanResult): string {
    return JSON.stringify(result, null, 2);
  }

  saveReport(content: string, filename: string, format: 'md' | 'json' = 'md'): string {
    const reportsDir = path.join(process.cwd(), 'reports');

    if (!fs.existsSync(reportsDir)) {
      fs.mkdirSync(reportsDir, { recursive: true });
    }

    const extension = format === 'md' ? 'md' : 'json';
    const filepath = path.join(reportsDir, `${filename}.${extension}`);

    fs.writeFileSync(filepath, content, 'utf-8');

    return filepath;
  }

  displayConsoleSummary(result: ScanResult): void {
    console.log('\n📊 Scan Summary:');
    console.log(`   Total Listings: ${result.scanned_listings}`);
    console.log(`   🔴 Critical: ${result.summary.critical}`);
    console.log(`   ⚠️  Warnings: ${result.summary.warnings}`);
    console.log(`   ℹ️  Info: ${result.summary.info}`);

    if (result.summary.critical > 0) {
      console.log('\n⚠️  ATTENTION: Critical violations found! Review immediately.');
    } else if (result.summary.warnings > 0) {
      console.log('\n⚠️  Warnings found. Review recommended.');
    } else if (result.summary.info > 0) {
      console.log('\nℹ️  Some suggestions available for improvement.');
    } else {
      console.log('\n✅ No violations found! Your shop is compliant.');
    }
  }
}
